# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: mdn

before:
  hooks:
    - go mod tidy

builds:
  - id: mdn
    main: ./cmd/mdn
    binary: mdn
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildDate={{.Date}}

universal_binaries:
  - id: mdn
    ids:
      - mdn
    replace: false

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ if eq .Arch "all" }}universal{{ else }}{{ .Arch }}{{ end }}

release:
  mode: keep-existing
  replace_existing_artifacts: true

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"
