package ui

import (
	"md-notes/internal/buffer"
)

// VisualLine represents a single rendered line on screen (either an entire logical line or a soft-wrapped segment).
type VisualLine struct {
	LogicalLine int    // 0-indexed line index in the buffer
	WrapIndex   int    // 0-indexed wrap segment (0 = head, 1+ = wrapped continuation)
	Text        string // Text content of this visual line
	StartCol    int    // Starting rune offset in the logical line
	EndCol      int    // Ending rune offset in the logical line
}

// VisualCoordinate represents the visual screen position of a cursor.
type VisualCoordinate struct {
	ScreenY int // 0-indexed visual line row on screen
	ScreenX int // 0-indexed visual column on screen (including gutter)
}

// Viewport handles window dimensions, scrolling, soft-wrap, and visual line rendering.
type Viewport struct {
	Width       int
	Height      int
	TopLine     int
	Scrolloff   int
	RelativeNum bool
	SoftWrap    bool
}

// NewViewport creates a new Viewport with standard defaults.
func NewViewport(w, h int) *Viewport {
	return &Viewport{
		Width:       w,
		Height:      h,
		TopLine:     0,
		Scrolloff:   4,
		RelativeNum: false,
		SoftWrap:    true,
	}
}

// SetDimensions updates the viewport width and height.
func (v *Viewport) SetDimensions(w, h int) {
	v.Width = w
	v.Height = h
	if v.Height < 1 {
		v.Height = 1
	}
	if v.Width < 1 {
		v.Width = 1
	}
}

// GetContentWidth returns the usable text width in the viewport (excluding gutter and scrollbar).
func (v *Viewport) GetContentWidth(totalLines int) int {
	gutterW := CalculateGutterWidth(totalLines)
	contentW := v.Width - gutterW - 1
	if contentW < 10 {
		contentW = 10
	}
	return contentW
}

// CountVisualLinesForLine returns the number of visual lines generated by a logical line.
func CountVisualLinesForLine(line buffer.Line, contentWidth int, softWrap bool) int {
	if !softWrap {
		return 1
	}
	rLen := line.Length()
	if rLen == 0 {
		return 1
	}
	if contentWidth <= 0 {
		contentWidth = 80
	}
	chunks := (rLen + contentWidth - 1) / contentWidth
	if chunks < 1 {
		return 1
	}
	return chunks
}

// TotalVisualLines returns the total count of visual lines across the entire buffer.
func (v *Viewport) TotalVisualLines(buf *buffer.Buffer) int {
	if buf == nil || buf.LineCount() == 0 {
		return 0
	}
	if !v.SoftWrap {
		return buf.LineCount()
	}
	contentW := v.GetContentWidth(buf.LineCount())
	total := 0
	for _, line := range buf.Lines {
		total += CountVisualLinesForLine(line, contentW, true)
	}
	return total
}

// CursorVisualRow computes the 0-indexed visual row corresponding to a cursor position in the buffer.
func (v *Viewport) CursorVisualRow(cursor buffer.Cursor, buf *buffer.Buffer) int {
	if buf == nil || buf.LineCount() == 0 {
		return 0
	}
	curLine := cursor.Line
	if curLine < 0 {
		curLine = 0
	}
	if curLine >= len(buf.Lines) {
		curLine = len(buf.Lines) - 1
	}

	if !v.SoftWrap {
		return curLine
	}

	contentW := v.GetContentWidth(buf.LineCount())
	vRow := 0
	for i := 0; i < curLine; i++ {
		vRow += CountVisualLinesForLine(buf.Lines[i], contentW, true)
	}

	chunksCount := CountVisualLinesForLine(buf.Lines[curLine], contentW, true)
	wrapIdx := 0
	if contentW > 0 {
		wrapIdx = cursor.Col / contentW
	}
	if wrapIdx >= chunksCount {
		wrapIdx = chunksCount - 1
	}
	if wrapIdx < 0 {
		wrapIdx = 0
	}
	return vRow + wrapIdx
}

// VisualRowToCursor maps a 0-indexed visual row back to logical line and column coordinates.
func (v *Viewport) VisualRowToCursor(targetVRow int, buf *buffer.Buffer) buffer.Cursor {
	if buf == nil || buf.LineCount() == 0 {
		return buffer.Cursor{Line: 0, Col: 0}
	}
	if targetVRow < 0 {
		targetVRow = 0
	}

	if !v.SoftWrap {
		if targetVRow >= buf.LineCount() {
			targetVRow = buf.LineCount() - 1
		}
		return buffer.Cursor{Line: targetVRow, Col: 0}
	}

	contentW := v.GetContentWidth(buf.LineCount())
	currentVRow := 0
	for i, line := range buf.Lines {
		chunksCount := CountVisualLinesForLine(line, contentW, true)
		if currentVRow+chunksCount > targetVRow {
			wrapIdx := targetVRow - currentVRow
			col := wrapIdx * contentW
			if col > line.Length() {
				col = line.Length()
			}
			return buffer.Cursor{Line: i, Col: col}
		}
		currentVRow += chunksCount
	}

	lastIdx := buf.LineCount() - 1
	return buffer.Cursor{Line: lastIdx, Col: 0}
}

// AdjustScroll updates TopLine based on cursor position and scrolloff margin.
func (v *Viewport) AdjustScroll(cursor buffer.Cursor, totalLines int) {
	if totalLines <= 0 {
		v.TopLine = 0
		return
	}

	curLine := cursor.Line
	if curLine < 0 {
		curLine = 0
	}
	if curLine >= totalLines {
		curLine = totalLines - 1
	}

	scrolloff := v.Scrolloff
	if scrolloff*2 >= v.Height {
		scrolloff = v.Height / 4
	}

	// Scroll up if cursor is within top scrolloff margin
	if curLine < v.TopLine+scrolloff {
		v.TopLine = curLine - scrolloff
		if v.TopLine < 0 {
			v.TopLine = 0
		}
	}

	// Scroll down if cursor is within bottom scrolloff margin
	bottomLimit := v.TopLine + v.Height - 1 - scrolloff
	if curLine > bottomLimit {
		v.TopLine = curLine - (v.Height - 1 - scrolloff)
		maxTop := totalLines - 1
		if v.TopLine > maxTop {
			v.TopLine = maxTop
		}
		if v.TopLine < 0 {
			v.TopLine = 0
		}
	}
}

// AdjustScrollWithBuffer updates TopLine based on visual lines taking soft-wrap into account.
func (v *Viewport) AdjustScrollWithBuffer(cursor buffer.Cursor, buf *buffer.Buffer) {
	if buf == nil || buf.LineCount() == 0 {
		v.TopLine = 0
		return
	}

	totalVisual := v.TotalVisualLines(buf)
	if totalVisual <= 0 {
		v.TopLine = 0
		return
	}

	cursorVisual := v.CursorVisualRow(cursor, buf)

	scrolloff := v.Scrolloff
	if scrolloff*2 >= v.Height {
		scrolloff = v.Height / 4
	}

	// Scroll up if cursor is within top scrolloff margin
	if cursorVisual < v.TopLine+scrolloff {
		v.TopLine = cursorVisual - scrolloff
		if v.TopLine < 0 {
			v.TopLine = 0
		}
	}

	// Scroll down if cursor is within bottom scrolloff margin
	bottomLimit := v.TopLine + v.Height - 1 - scrolloff
	if cursorVisual > bottomLimit {
		v.TopLine = cursorVisual - (v.Height - 1 - scrolloff)
		maxTop := totalVisual - 1
		if v.TopLine > maxTop {
			v.TopLine = maxTop
		}
		if v.TopLine < 0 {
			v.TopLine = 0
		}
	}
}

// ScrollDown scrolls the viewport down by delta visual lines, adjusting the cursor if needed.
func (v *Viewport) ScrollDown(delta int, buf *buffer.Buffer) {
	if buf == nil || buf.LineCount() == 0 || delta <= 0 {
		return
	}
	totalVisual := v.TotalVisualLines(buf)
	maxTop := totalVisual - v.Height
	if maxTop < 0 {
		maxTop = 0
	}
	v.TopLine += delta
	if v.TopLine > maxTop {
		v.TopLine = maxTop
	}

	cursorVisual := v.CursorVisualRow(buf.Cursor, buf)
	minVisual := v.TopLine
	if cursorVisual < minVisual {
		buf.Cursor = v.VisualRowToCursor(minVisual, buf)
	}
}

// ScrollUp scrolls the viewport up by delta visual lines, adjusting the cursor if needed.
func (v *Viewport) ScrollUp(delta int, buf *buffer.Buffer) {
	if buf == nil || buf.LineCount() == 0 || delta <= 0 {
		return
	}
	v.TopLine -= delta
	if v.TopLine < 0 {
		v.TopLine = 0
	}

	totalVisual := v.TotalVisualLines(buf)
	cursorVisual := v.CursorVisualRow(buf.Cursor, buf)
	maxVisual := v.TopLine + v.Height - 1
	if maxVisual >= totalVisual {
		maxVisual = totalVisual - 1
	}
	if cursorVisual > maxVisual && maxVisual >= 0 {
		buf.Cursor = v.VisualRowToCursor(maxVisual, buf)
	}
}

// WrapLogicalLine breaks a single buffer line into VisualLine segments fitting within contentWidth.
func WrapLogicalLine(logicalIdx int, line buffer.Line, contentWidth int) []VisualLine {
	runes := line.Runes
	if len(runes) == 0 {
		return []VisualLine{
			{
				LogicalLine: logicalIdx,
				WrapIndex:   0,
				Text:        "",
				StartCol:    0,
				EndCol:      0,
			},
		}
	}

	if contentWidth <= 0 {
		contentWidth = 80
	}

	var visualLines []VisualLine
	totalRunes := len(runes)
	wrapIdx := 0

	for start := 0; start < totalRunes; start += contentWidth {
		end := start + contentWidth
		if end > totalRunes {
			end = totalRunes
		}
		visualLines = append(visualLines, VisualLine{
			LogicalLine: logicalIdx,
			WrapIndex:   wrapIdx,
			Text:        string(runes[start:end]),
			StartCol:    start,
			EndCol:      end,
		})
		wrapIdx++
	}

	return visualLines
}

// LogicalToVisual maps logical buffer coordinates (Line, Col) to screen coordinates (ScreenY, ScreenX).
func LogicalToVisual(cursor buffer.Cursor, visualLines []VisualLine, gutterWidth int) VisualCoordinate {
	for screenY, vLine := range visualLines {
		if vLine.LogicalLine == cursor.Line {
			if cursor.Col >= vLine.StartCol && (cursor.Col < vLine.EndCol || (cursor.Col == vLine.EndCol && vLine.WrapIndex == 0)) {
				screenX := (cursor.Col - vLine.StartCol) + gutterWidth
				return VisualCoordinate{ScreenY: screenY, ScreenX: screenX}
			}
		}
	}
	return VisualCoordinate{ScreenY: 0, ScreenX: gutterWidth}
}

// GetVisibleLines computes the visual lines to render for the current viewport view.
func (v *Viewport) GetVisibleLines(buf *buffer.Buffer) []VisualLine {
	if buf == nil || buf.LineCount() == 0 {
		return nil
	}

	totalLines := buf.LineCount()
	contentW := v.GetContentWidth(totalLines)
	totalVisual := v.TotalVisualLines(buf)

	start := v.TopLine
	if start < 0 {
		start = 0
	}
	if start >= totalVisual {
		start = totalVisual - 1
		if start < 0 {
			start = 0
		}
	}

	targetCount := v.Height
	if targetCount < 1 {
		targetCount = 1
	}

	var visibleLines []VisualLine
	currentVisualIdx := 0

	for i := 0; i < totalLines; i++ {
		line, _ := buf.GetLine(i)
		var chunks []VisualLine
		if v.SoftWrap {
			chunks = WrapLogicalLine(i, line, contentW)
		} else {
			raw := line.String()
			chunks = []VisualLine{{
				LogicalLine: i,
				WrapIndex:   0,
				Text:        raw,
				StartCol:    0,
				EndCol:      len(line.Runes),
			}}
		}

		lineVisualCount := len(chunks)
		if currentVisualIdx+lineVisualCount > start && currentVisualIdx < start+targetCount {
			for chunkIdx, chunk := range chunks {
				globalVIdx := currentVisualIdx + chunkIdx
				if globalVIdx >= start && globalVIdx < start+targetCount {
					visibleLines = append(visibleLines, chunk)
				}
			}
		}

		currentVisualIdx += lineVisualCount
		if currentVisualIdx >= start+targetCount {
			break
		}
	}

	return visibleLines
}
